Feedapp/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.Login,name='login'),
    path('getfeedback/<str:pk>',views.getFeedback,name='submitfeedback'),
    path('logout',views.Logout,name='logout'),
    path('oops',views.oops,name='oops'),
]

Feedback/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Feedapp.urls')),
    path('T/',include('Trainee.urls')),
    path('E/',include('Employee.urls'))
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
admin.autodiscover()
admin.site.enable_nav_sidebar = False
admin.site.site_header = "CTTC Feedback Administration"
admin.site.site_title = "CFS"

Employee/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from Feedapp.models import Course,Department
from django.utils.translation import ugettext_lazy as _
# Create your models here.

class EmployeeProfile(models.Model):
    class DesignationChoices(models.TextChoices):
        D1 = "GM",_("General Manager")
        D2 = "SM",_("Senior Manager")
        D3 = "MR",_("Manager")
        D4 = "SE",_("Senior Engineer")
        D5 = "ER",_("Engineer")
        D6 = "MC",_("Master Craftsman")
        D7 = "CO",_("Consultant")
        D8 = "GE",_("Graduate Engineer Trainee")
        D9 = "DE",_("Diploma Engineer Trainee")
        D10= "OJ",_("On Job Trainee")

    user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
    department = models.ForeignKey(Department,to_field="department_name",on_delete=models.DO_NOTHING,blank=True,null=True)
    desg = models.TextField(_("Designation"),max_length=10,choices=DesignationChoices.choices,blank=True)
    qual = models.TextField(_("Qualification"),max_length=20,blank=True)
    photo = models.ImageField(upload_to='Employee_Photos',default='default_avatar.png')
    phone = models.IntegerField(null=True,blank=True)

    def __str__(self):
        return self.user.first_name+' '+'profile'

    def __getUser__(self):
        return self.user

Feedapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

# from Employee.models import EmployeeProfile
# from Trainee.models import TraineeProfile
# Create your models here.

class Department(models.Model):

    class DepartmentChoices(models.TextChoices):
        D1 = "PGDTD",_("Post Graduate Diploma in Tool Design")
        D2 = "MCC",_("Master Certificate Course In CAD/CAM")
        D3 = "PDTDM",_("Post Diploma In Tool and Die Making")
        D4 = "PDCC",_("Post Diploma in CAD/CAM")
        D5 = "CNC",_("Computer Numeric Control")
        D6 = "ITI",_("ITI")
        D7 = "DDUGKY",_("DDUGKY")
        D8 = "CIVIL",_("CIVIL")
        D9 = "DTDM",_("Diploma In Tool and Die Making")
        D10= "DIM",_("Diploma in Mechatronics")
        D11= "MCCAPC",_("MCCAPC")
        D12="ADMA",_("ADMA")
        D13="IoT",_("Internet Of Things")
        D14="PE",_("Power Electronics")
        D15="VLSI",_("Very Large Scale Integration")
        D16="OT",_("Others")

    department_name = models.TextField(max_length=20,choices=DepartmentChoices.choices,primary_key=True)
    incharge = models.ForeignKey(User,on_delete=models.DO_NOTHING,blank=True,null=True)
    section = models.TextField(max_length=10,choices=(("CAD","CAD/CAM"),
    ("EB","Electronics Block"),("CV","Civil")),default="CAD")

    def __str__(self):
        return self.department_name
        



class Course(models.Model):

    course_id = models.CharField(max_length=50,primary_key=True)
    subject   = models.CharField(max_length=50,default='Others')
    course_details = models.CharField(max_length=500,blank=False)
    faculty    = models.ForeignKey("Employee.EmployeeProfile", verbose_name=_("Faculty"), on_delete=models.CASCADE)
    start_date = models.DateField(blank=True)
    end_date   = models.DateField(blank=True)
    start_time = models.TimeField(blank=True)
    end_time   = models.TimeField(blank=True)
    venue      = models.CharField(max_length=10,blank=True)
    def __str__(self):
        return self.course_id

class FeedBackQuestions(models.Model):

    Q1 = models.TextField(max_length=100,blank =False)
    Q2 = models.TextField(max_length=100,blank=False)
    Q3 = models.TextField(max_length=100,blank=False)
    Q4 = models.TextField(max_length=100,blank=False)
    Q5 = models.TextField(max_length=100,blank=False)
    Q6 = models.TextField(max_length=100,blank=False)
    Q7 = models.TextField(max_length=100,blank=False)
    Q8 = models.TextField(max_length=100,blank=False)
    Q9 = models.TextField(max_length=100,blank=False)
    Q10 = models.TextField(max_length=100,blank=False)
    Q11 = models.TextField(max_length=100,blank=False)
    Q12 = models.TextField(max_length=100,blank=False)
    Q13 = models.TextField(max_length=100,blank=False,default="Safety")
    Q14 = models.TextField(max_length=100,blank=False,default="Training Admin Response")
    Q15 = models.TextField(max_length=100,blank=False,default="Cafeteria")
    Q16 = models.TextField(max_length=100,blank=False,default="Sanitation")
    Q17 = models.TextField(max_length=100,blank=False,default="Whether Course Duration is")
    Q18 = models.TextField(max_length=100,blank=False,default='Course To Be recommended')

    def __str__(self):
        return 'Feeback Questions Do not Add new'

    class Meta:
        verbose_name_plural = 'Feedback Questions'

class FeedBack(models.Model):

    class AmenitiesChoices(models.TextChoices):
        AM1 = "POOR",_("POOR")
        AM2 = "SATS",_("SATISFACTORY")
        AM3 = "GOOD" ,_("GOOD")
        AM4 = "EXCL",_("EXCELLENT")

    course_id = models.ForeignKey(Course,on_delete=models.CASCADE)
    user      = models.ForeignKey(User,on_delete=models.CASCADE)
    A1        = models.IntegerField(_("How well the course was organised?"),choices=list(zip(range(2, 11), range(2, 11))),blank=False)
    A2        = models.IntegerField(_("How confident do you feel about your grasp of this module content ?"),choices=list(zip(range(2, 11), range(2, 11))),blank=False)
    A3        = models.IntegerField(_("How do you rate the learning environment during your training?"),choices=list(zip(range(2, 11), range(2, 11))),blank=False)
    A4        = models.IntegerField(_("How satisfied you are by the training facility provided to you?"),choices=list(zip(range(2, 11), range(2, 11))),blank=False)
    A5        = models.IntegerField(_("How was the quality of study material provided to you?"),choices=list(zip(range(2, 11), range(2, 11))),blank=False)
    A6        = models.IntegerField(_("How effective do you find the faculty?"),choices=list(zip(range(2, 11), range(2, 11))),blank=False)
    A7        = models.IntegerField(_("How satisfactory did you find their answers to your queries?"),choices=list(zip(range(2, 11), range(2, 11))),blank=False)
    A8        = models.IntegerField(_("How thorough was their knowledge of course contents?"),choices=list(zip(range(2, 11), range(2, 11))),blank=False)
    A9        = models.IntegerField(_("How inspiring was your association with the faculty?"),choices=list(zip(range(2, 11), range(2, 11))),blank=False)
    A10       = models.IntegerField(_("How do you rate the assistance provided during your training?"),choices=list(zip(range(2, 11), range(2, 11))),blank=False)
    A11       = models.IntegerField(_("How effective was the consultation provided?"),choices=list(zip(range(2, 11), range(2, 11))),blank=False)
    A12       = models.IntegerField(_("How well were the stated objectives of the module achieved?"),choices=list(zip(range(2, 11), range(2, 11))),blank=False)
    A13       = models.CharField(_("Safety"),max_length=4,choices=AmenitiesChoices.choices)
    A14       = models.CharField(_("Training Admin Response"),max_length=4,choices=AmenitiesChoices.choices)
    A15       = models.CharField(_("Cafeteria"),max_length=4,choices=AmenitiesChoices.choices)
    A16       = models.CharField(_("Sanitation"),max_length=4,choices=AmenitiesChoices.choices)
    A17       = models.CharField(_("Whether Course Duration is"),max_length=2,choices=(("TS","Too Short"),("AD","Adequate"),("TL","Too Long")))
    A18       = models.CharField(_("Course To Be recommended"),max_length=2,choices=(("Y","Yes"),("N","No")))
    comments  = models.TextField(_("Comments"),max_length=300,default="No Comments")
    def __str__(self):
        return "{} {}".format(self.user.first_name+' '+self.user.last_name,self.course_id)
    class Meta:
        verbose_name_plural = 'Feedbacks'
    

templates/EmployeeProfile.html
{% extends 'EmployeeBase.html' %}
{% load static %}
{% block title %}Employee Profile{% endblock %}

{% block style %}
<style>
     
   .rateHeader {
      font-size: 25px;
      margin-right: 25px;
   }
   .fa {
      font-size: 25px;
      color: grey;
   }
   .ratedg {
      color: rgb(115, 255, 0);
      border: none;
   }
   .ratedo {
      color: rgb(255, 174, 0);
      border: none;
   }
   .data {
      float: left;
      width: 15%;
      margin-top: 10px;
      font-weight: bold;
   }
   .progressBar {
      margin-top: 10px;
      float: left;
      width: 70%;
   }
   .right {
      text-align: right;
   }
   .row:after {
      content: "";
      display: table;
      clear: both;
   }
   .progressContainer {
      width: 100%;
      background-color: #f1f1f1;
      text-align: center;
      color: white;
      border-radius: 10px;
   }
   .bar-1, .bar-2, .bar-3, .bar-4, .bar-5 {
      border-radius: 10px;
   }
   .bar-5 {
      width: {{ star_percent.0 }}%;
      height: 18px;
      background-color: rgb(76, 175, 162);
   }
   .bar-4 {
      width: {{star_percent.1}}%;
      height: 18px;
      background-color: rgb(243, 222, 33);
   }
   .bar-3 {
      width: {{star_percent.2}}%;
      height: 18px;
      background-color: #12d400;
   }
   .bar-2 {
      width: {{star_percent.3}}%;
      height: 18px;
      background-color: #ff0055;
   }
   .bar-1 {
      width: {{star_percent.4}}%;
      height: 18px;
      background-color: #a836f4;
   }
</style>
{% endblock %}

{% block content %}
<div class="main-content">

                  <div class = "container-fluid">
                    <div class="row">
                    <div class="col-lg-2"></div>
                      <div class="col-lg-9">
                      {% if messages %}
                          {% for message in messages %}
                              {% if message.tags == 'error' %}
                                  <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show">
                                          <span class="badge badge-pill badge-danger">Alert!!</span>
                                          {{ message }}
                                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                              <span aria-hidden="true">&times;</span>
                                          </button>
                                  </div>
                              
                              {% else %}
                                  <div class="sufee-alert alert with-close alert-success alert-dismissible fade show">
                                      <span class="badge badge-pill badge-success">Alert!!</span>
                                      {{ message }}
                                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                      </button>
                                  </div>
                              {% endif %}
                          {% endfor %}
                      {% endif %}
                      </div>
                    </div>
                    </div>



                            <div class="col-md-4">
                                <div class="card">
                                    <div class="card-header">
                                        <strong class="card-title mb-3">Faculty Profile</strong>
                                    </div>
                                    <div class="card-body">
                                       <div class="mx-auto d-block">
                                            <img class="user mx-auto d-block" src="{{pro.photo.url}}" alt="Card image cap">
                                            <h5 class="text-sm-center mt-2 mb-1">{{pro.user.first_name}}&nbsp;{{pro.user.last_name}}</h5>
                                       </div>
                                       <hr>
                                       <div class="card-text">
                                            
                                                Designation :- {{pro.get_desg_display}}
                                            
                                       </div>
                                       <div class="card-text">
                                          
                                               Department :- {{pro.department}}
                                          
                                       </div>
                                       <div class="card-text">
                                          
                                                Phone :- {{pro.phone}}
                                          
                                       </div>


                                    </div>
                                    <div class="card-footer">
                                    
                                                <span class="rateHeader">User Rating</span>
                                                {% if avg >= 4 %}
                                                {% for i in flag %}
                                                <span class="fa fa-star ratedg"></span>
                                                {% endfor %}
                                                {% else %}
                                                {% for i in flag %}
                                                <span class="fa fa-star ratedo"></span>
                                                {% endfor %}
                                                {% endif %}
                                                <p>{{avg}} average based on {{total_stars}} feedbacks</p>
                                                <div class="row">
                                                <div class="data">
                                                <div>5 star</div>
                                                </div>
                                                <div class="progressBar">
                                                <div class="progressContainer">
                                                <input type="hidden" id="myVar" name="variable" value="{{ star_percent.0 }}">
                                                <div class="bar-5"></div>
                                                </div>
                                                </div>
                                                <div class="data right">
                                                <div>{{count_stars.0}}</div>
                                                </div>
                                                <div class="data">
                                                <div>4 star</div>
                                                </div>
                                                <div class="progressBar">
                                                <div class="progressContainer">
                                                <div class="bar-4"></div>
                                                </div>
                                                </div>
                                                <div class="data right">
                                                <div>{{count_stars.1}}</div>
                                                </div>
                                                <div class="data">
                                                <div>3 star</div>
                                                </div>
                                                <div class="progressBar">
                                                <div class="progressContainer">
                                                <div class="bar-3"></div>
                                                </div>
                                                </div>
                                                <div class="data right">
                                                <div>{{count_stars.2}}</div>
                                                </div>
                                                <div class="data">
                                                <div>2 star</div>
                                                </div>
                                                <div class="progressBar">
                                                <div class="progressContainer">
                                                <div class="bar-2"></div>
                                                </div>
                                                </div>
                                                <div class="data right">
                                                <div>{{count_stars.3}}</div>
                                                </div>
                                                <div class="data">
                                                <div>1 star</div>
                                                </div>
                                                <div class="progressBar">
                                                <div class="progressContainer">
                                                <div class="bar-1"></div>
                                                </div>
                                                </div>
                                                <div class="data right">
                                                <div>{{count_stars.4}}</div>
                                                </div>
                                                </div>
                                    
                                    </div>
                                </div>
                            </div>

</div>
{% endblock %}

templates/feedbackform.html
{% extends 'TraineeBase.html' %}
{% block title %}Give Feedback{% endblock %}

{% block content %}

            <div class="main-content">
                <div class="row">
                    <div class="col-lg-6">
                    {% if messages %}
                        {% for message in messages %}
                            {% if message.tags == 'error' %}
                                <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show">
                                        <span class="badge badge-pill badge-danger">Alert!!</span>
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                </div>
                            
                            {% else %}
                                <div class="sufee-alert alert with-close alert-success alert-dismissible fade show">
                                    <span class="badge badge-pill badge-success">Alert!!</span>
                                    {{ message }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    </div>
                </div> 
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <p class="text-right">F/CTTC/BBSR/TRG/SPV</p>
                         
                        <div class="card">
                            <div class="card-header">
                                <div class="row">
                                    <div class="col-6">
                                        <strong>Learning Service Validation</strong>
                                        :- Please provide your Valuable Feedback
                                    </div>
                                    <div class="col-6">
                                        <p class="text-right"><strong>Rating Scale :</strong> 2-4 Poor&nbsp;&nbsp;|&nbsp;&nbsp;5-6 Average&nbsp;&nbsp;|&nbsp;&nbsp;7-8 Good&nbsp;&nbsp;|&nbsp;&nbsp;9-10 Excellent</p>
                                    </div> 
                                </div>
                            </div>
                            <div class="card-body card-block">
                                <form action="{% url 'submitfeedback' pk %}" method="post" enctype="multipart/form-data" class="form-horizontal">
                                    {% csrf_token %}
                                    
                                    {% for element in form %}
                                    {% if element.label == 'Comments' %}
                                    <div class="row form-group">
                                        <div class="col-12 col-md-9">
                                            <label for="{{ element.id_for_label }}" class=" form-control-label">{{ element.label }}</label>
                                        </div>
                                        <div class="col-lg-6">
                                            {{element}}
                                        </div>
                                        
                                    </div>
                                    <hr>
                                    {% elif not element.is_hidden and element.label != 'Course id' and element.label != 'How do you rate Safety?' and element.label != 'How do you rate Training Admin Response?' and element.label != 'How do you rate Cafeteria?' and element.label != 'How do you rate Sanitation?' and element.label != 'Whether Course Duration is' and element.label != 'Course To Be recommended' %}
                                    <div class="row form-group">
                                        <div class="col-lg-6">
                                            <label for="{{ element.id_for_label }}" class=" form-control-label"><strong>{{ element.label }}</strong></label>
                                        </div>
                                        <div class="col-lg-6">
                                            {{ element }}
                                            
                                        </div>
                                        <!-- <div class="col-12 col-md-9">
                                            &nbsp;
                                        </div>  -->
                                        <!-- <div class="col-12 col-md-9">
                                            <p class="text-right">2-4 Poor&nbsp;&nbsp;|&nbsp;&nbsp;5-6 Average&nbsp;&nbsp;|&nbsp;&nbsp;7-8 Good&nbsp;&nbsp;|&nbsp;&nbsp;9-10 Excellent</p>
                                        </div>  -->
                                    </div>
                                    <br>
                                    <hr>
                                    {% elif element.label == 'How do you rate Safety?' or element.label == 'How do you rate Training Admin Response?' or element.label == 'How do you rate Cafeteria?' or element.label == 'How do you rate Sanitation?' or element.label == 'Whether Course Duration is' or element.label == 'Course To Be recommended' %}
                                    <div class="row form-group">
                                        <div class="col-lg-6">
                                            <label for="{{ element.id_for_label }}" class=" form-control-label"><strong>{{ element.label }}</strong></label>
                                        </div>
                                        <!-- <div class="col-12 col-md-9">
                                            &nbsp;
                                        </div> -->
                                        <div class="col-lg-6">
                                            {{ element }}
                                        </div>
                                        <div class="col-12 col-md-9">
                                            &nbsp;
                                        </div> 
                                    </div>
                                    <br>
                                    <hr>
                                    {% elif element.label == 'Course id' %}
                                    <div class="row form-group">
                                        <div class="col-12 col-md-9">
                                            <label for="{{ element.id_for_label }}" class=" form-control-label"><strong>{{ element.label }}</strong></label>
                                        </div>
                                        <div class="col-12 col-md-9">
                                            {{ element }}
                                        </div>
                                        
                                    </div>
                                    <hr>
                                    {% else %}
                                    <div class="row form-group">
                                        <div class="col-12 col-md-9">
                                            <label for="{{ element.id_for_label }}" class=" form-control-label"><strong>Name</strong></label>
                                            :-&nbsp;{{element}}{{name}}
                                        </div> 
                                    </div>
                                    <hr>
                                    {% endif %}
                                    {% endfor %}
                                    <button type="submit" class="btn btn-primary btn-sm">
                                        <i class="fa fa-dot-circle-o"></i> Submit
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
<script type="text/javascript">
            $(function() {
                $('#id_A1').barrating({
                theme: 'bars-square',
                showValues: true,
                showSelectedRating: false,
                initialRating:false
                });
            });
            $(function() {
                $('#id_A2').barrating({
                theme: 'bars-square',
                showValues: true,
                showSelectedRating: false,
                initialRating:false
                });
            });
            $(function() {
                $('#id_A3').barrating({
                theme: 'bars-square',
                showValues: true,
                showSelectedRating: false,
                initialRating:false
                });
            });
            $(function() {
                $('#id_A4').barrating({
                theme: 'bars-square',
                showValues: true,
                showSelectedRating: false,
                initialRating:false
                });
            });
            $(function() {
                $('#id_A5').barrating({
                theme: 'bars-square',
                showValues: true,
                showSelectedRating: false,
                initialRating:false
                });
            });
            $(function() {
                $('#id_A6').barrating({
                theme: 'bars-square',
                showValues: true,
                showSelectedRating: false,
                initialRating:false
                });
            });
            $(function() {
                $('#id_A7').barrating({
                theme: 'bars-square',
                showValues: true,
                showSelectedRating: false,
                initialRating:false
                });
            });
            $(function() {
                $('#id_A8').barrating({
                theme: 'bars-square',
                showValues: true,
                showSelectedRating: false,
                initialRating:false
                });
            });
            $(function() {
                $('#id_A9').barrating({
                theme: 'bars-square',
                showValues: true,
                showSelectedRating: false,
                initialRating:false
                });
            });
            $(function() {
                $('#id_A10').barrating({
                theme: 'bars-square',
                showValues: true,
                showSelectedRating: false,
                initialRating:false
                });
            });
            $(function() {
                $('#id_A11').barrating({
                theme: 'bars-square',
                showValues: true,
                showSelectedRating: false,
                initialRating:false
                });
            });
            $(function() {
                $('#id_A12').barrating({
                theme: 'bars-square',
                showValues: true,
                showSelectedRating: false,
                initialRating:false
                });
            });
            $(function() {
                $('#id_A13').barrating({
                theme: 'bars-movie',
                showValues: false,
                showSelectedRating: true,
                });
            });
            $(function() {
                $('#id_A14').barrating({
                theme: 'bars-movie',
                showValues: false,
                showSelectedRating: true,
                });
            });
            $(function() {
                $('#id_A15').barrating({
                theme: 'bars-movie',
                showValues: false,
                showSelectedRating: true,
                });
            });
            $(function() {
                $('#id_A16').barrating({
                theme: 'bars-movie',
                showValues: false,
                showSelectedRating: true,
                });
            });
</script>
{% endblock %}